# Generated by Django 5.2.6 on 2025-09-17 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento')),
                ('telefono', models.IntegerField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Servicio')),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, max_length=15, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(max_length=100, verbose_name='Turno')),
                ('costo', models.IntegerField()),
                ('observaciones', models.CharField(max_length=100)),
                ('fecha_hora', models.DateField()),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.cliente')),
                ('nombre_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.empleado')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.servicios')),
            ],
        ),
    ]
