# Generated by Django 5.2.6 on 2025-09-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_user_apellido_alter_user_nombre'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
